# Generated by Django 5.2.10 on 2026-01-31 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('why', models.TextField()),
                ('owner', models.TextField()),
                ('horizon', models.CharField(max_length=20)),
                ('impact', models.CharField(max_length=10)),
                ('metric', models.TextField()),
                ('is_done', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'action_items',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('organization', models.TextField(blank=True, null=True)),
                ('total_given', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_gift_date', models.DateTimeField()),
                ('last_gift_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donors',
                'ordering': ['-total_given'],
            },
        ),
        migrations.CreateModel(
            name='DueItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('owner', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'due_items',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('to_team', models.TextField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
